config/routes.rb
Rails.application.routes.draw do
  resources :surveys
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'surveys#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question, required: false
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :survey, required: false #http://stackoverflow.com/questions/39359168/rails-nested-form-error-child-must-exist
  has_many :answers, :dependent => :destroy
  accepts_nested_attributes_for :answers, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
end

app/models/survey.rb
class Survey < ApplicationRecord
    has_many :questions, :dependent => :destroy
    accepts_nested_attributes_for :questions, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:show, :edit, :update, :destroy]

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
  end

  # GET /surveys/new
  def new
    @survey = Survey.new

    #2.times do
      #question = @survey.questions.build
      #2.times { question.answers.build }
    #end
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(survey_params)

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: 'Survey was successfully created.' }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: 'Survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      params.require(:survey).permit(:content, questions_attributes: [:id, :content, :_destroy, answers_attributes: [:id, :content, :_destroy]])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testsurvey</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/surveys/_form.html.erb
<%= nested_form_for (survey) do |f| %>
  <% if survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% survey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_field :content, :class=>"form-control" %>
  </div>
 
  <div class="panel panel-default">
    <div class="panel-body">
      
      <%= f.fields_for :questions do |question_form| %>
        <h3>Question</h3>
          <div class="input-group">
            <!--input type="text" class="form-control"-->
            <%= question_form.text_field :content, :class=>"form-control" %>
            <span class="input-group-btn">
                  <!--button class="btn btn-default" type="button">Go!</button-->
                  <%= question_form.link_to_remove "Remove this question", :class=>"btn btn-danger"  %>
            </span>
          </div>

        
        


        <!--div class="panel panel-default">
          <div class="panel-body"-->
            
              <h4>Answers</h4>
            <%= question_form.fields_for :answers do |answer_form| %>
            

              <div class="input-group">
                <%= answer_form.text_field :content, :class=>"form-control" %>
                <span class="input-group-btn">
                      <!--button class="btn btn-default" type="button">Go!</button-->
                      <%= answer_form.link_to_remove "Remove this answer", :class=>"btn btn-danger" %>
                </span>
              </div>
              </br>
              
              
            <% end %>
            </br>
          <!--/div>
        </div-->

          
          <p><%= question_form.link_to_add "Add a answer", :answers, :class=>"btn btn-primary" %></p>

          <hr>
      <% end %>

      <p><%= f.link_to_add "Add a question", :questions, :class=>"btn btn-primary" %></p>
      <hr>
      
    </div>
  </div>

  

  

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/surveys/edit.html.erb
<h1>Editing Survey</h1>

<%= render 'form', survey: @survey %>

<%= link_to 'Show', @survey, class: 'btn btn-primary' %> |
<%= link_to 'Back', surveys_path, class: 'btn btn-default' %>

app/views/surveys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Surveys</h1>

<table class="table">
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @surveys.each do |survey| %>
      <tr>
        <td><%= survey.content %></td>
        <td><%= link_to 'Show', survey, class: 'btn btn-primary btn-xs' %></td>
        <td><%= link_to 'Edit', edit_survey_path(survey), class: 'btn btn-primary btn-xs' %></td>
        <td><%= link_to 'Destroy', survey, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Survey', new_survey_path, class: 'btn btn-default' %>

app/views/surveys/new.html.erb
<h1>New Survey</h1>

<%= render 'form', survey: @survey %>

<%= link_to 'Back', surveys_path %>

app/views/surveys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @survey.content %>
</p>

<ol>
<% for question in @survey.questions %>
  <li>
    <%= question.content %>
    <ul>
    <% for answer in question.answers %>
      <li><%= answer.content %></li>
    <% end %>
    </ul>
  </li>
<% end %>
</ol>

<div class="row pull-rigth">
  <%= link_to 'Edit', edit_survey_path(@survey), class: 'btn btn-primary' %> 
  <%= link_to 'Back', surveys_path, class: 'btn btn-default' %>
</div>